#!/bin/bash
#
# Wrapper around `patch` which provides some convenience features
# 1) The wrapper searches for the `patch` binary in ${PATH}
#
set -e

# Kapitan provides a fairly standard PATH variable, we add /opt/homebrew/bin for macOS
export PATH="${PATH}:/opt/homebrew/bin"

cmdname="${1}"
shift

cmd=$(which "${cmdname}") || (>&2 echo "${cmdname} not found in ${PATH}"; exit 7)

exec "$cmd" "${@}"
