= Parameters

The parent key for all of the following parameters is `mimir`.

The component allows multi instantiation.

The underlying Helm chart can be found https://github.com/grafana/mimir/tree/main/operations/helm/charts/mimir-distributed[here].

== `namespace.name`

[horizontal]
type:: string
default:: `syn-mimir`

The namespace in which to deploy this component.


== `namespace.create`

[horizontal]
type:: boolean
default:: `true`

Wether to create the namespace given by `namespace.name`.


== `namespace.metadata`

[horizontal]
type:: dict
default:: `{}`
example:: `{"labels": {"organization": "bar"}}`

Additional metadata to add to the namespace.


== `charts`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
mimir-distributed:
  source: https://grafana.github.io/helm-charts
  version: '4.3.0'
----

Holds the reference to the used version of the charts.
See https://github.com/projectsyn/component-mimir/blob/master/class/defaults.yml[class/defaults.yml] for the current version.


== `images`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
images:
  mimir:
    registry: docker.io
    repository: grafana/mimir
  memcached:
    registry: docker.io
    repository: library/memcached
  memcachedExporter:
    registry: docker.io
    repository: prom/memcached-exporter
  nginx:
    registry: docker.io
    repository: nginxinc/nginx-unprivileged
  rolloutOperator:
    registry: docker.io
    repository: grafana/rollout-operator
----
example::
+
[source,yaml]
----
images:
  mimir:
    registry: my-docker-cache.example.org
    tag: latest
  memcached:
    tag: latest
  memcachedExporter:
    tag: latest
  nginx:
    tag: latest
  rolloutOperator:
    tag: latest
----

Configures the image registry, repository and tag.

[INFO]
----
If the `tag` parameter is not set, the one from the Helm chart will be used.
----


== `preset`

[horizontal]
type:: string
default:: `small`

Choose a preset for scaling the Mimir components.

Available options: none, extra-small, small, large.


== `components`

Configuration of the different Mimir components.

[INFO]
----
The values of each component reflect the corresponding sections in the Helm charts `values.yaml` file.
----

Read path: querier, queryFrontend, queryScheduler, storeGateway.
Write path: distributor, ingester.
Backend: compactor, rolloutOperator.
Ingress: nginx, gateway.
Optional: alertmanager, overridesExporter, ruler.

=== `components.querier`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
components:
  querier:
    enabled: true
----

The querier is a stateless component that evaluates PromQL expressions by fetching time series and labels on the read path.

The querier uses the store-gateway component to query the long-term storage and the ingester component to query recently written data.

=== `components.queryFrontend`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
components:
  queryFrontend:
    enabled: true
----

The query-frontend is a stateless component that provides a Prometheus compatible API with a number of features to accelerate the read path.
The query-frontend is the primary entry point for the read path of Mimir.
The query-scheduler and queriers are required within the cluster to execute the queries.

We recommend that you run at least two query-frontend replicas for high-availability reasons.

=== `components.queryScheduler`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
components:
  queryScheduler:
    enabled: true
----

The query-scheduler is stateless component that retains a queue of queries to execute, and distributes the workload to available queriers.

=== `components.storeGateway`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
components:
  storeGateway:
    enabled: true
    storage: {}
----

The store-gateway component, which is stateful, queries blocks from long-term storage.
On the read path, the querier and the ruler use the store-gateway when handling the query, whether the query comes from a user or from when a rule is being evaluated.


=== `components.distributor`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
components:
  distributor:
    enabled: true
----

The distributor is a stateless component that acts as the entry point for the Grafana Mimir write path.
It receives incoming write requests containing time series data, validates the data for correctness, enforces tenant-specific limits, and then ingests the data into Mimir.

=== `components.ingester`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
components:
  ingester:
    enabled: true
    storage: {}
----

The ingester is a stateful component that processes the most recently ingested samples and makes them available for querying.
Queriers read recent data from ingesters and older data from long-term object storage via store-gateways.


=== `components.compactor`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
components:
  compactor:
    enabled: true
----

The compactor increases query performance and reduces long-term storage usage by combining blocks.

Compacting multiple blocks of a given tenant into a single, optimized larger block.
This deduplicates chunks and reduces the size of the index, resulting in reduced storage costs.
Querying fewer blocks is faster, so it also increases query speed.

=== `components.rolloutOperator`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
components:
  rolloutOperator:
    enabled: true
----


=== `components.alertmanager`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
components:
  alertmanager:
    enabled: true
      overridesExporter:
        enabled: true
      ruler:
        enabled: true
----

The Mimir Alertmanager adds multi-tenancy support and horizontal scalability to the Prometheus Alertmanager.
The Mimir Alertmanager is an optional component that accepts alert notifications from the Mimir ruler.

=== `components.overridesExporter`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
components:
  overridesExporter:
    enabled: true
----

Grafana Mimir supports applying overrides on a per-tenant basis.
A number of overrides configure limits that prevent a single tenant from using too many resources.
The overrides-exporter component exposes limits as Prometheus metrics so that operators can understand how close tenants are to their limits.

=== `components.ruler`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
components:
  ruler:
    enabled: true
----

The ruler is an optional component that evaluates PromQL expressions defined in recording and alerting rules.
Each tenant has a set of recording and alerting rules and can group those rules into namespaces.


== `caches`

Configuration of the cache components of Mimir.
Caching is optional, but highly recommended in a production environment.

[INFO]
----
The values of each component reflect the corresponding sections in the Helm charts `values.yaml` file.
----

=== `caches.chunks`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
caches:
  chunks:
    enabled: true
----

The store-gateway can also use a cache to store chunks that are fetched from long-term storage.
Chunks contain actual samples, and can be reused if a query hits the same series for the same time range.

=== `caches.index`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
caches:
  index:
    enabled: true
----

The store-gateway can use the index cache to accelerate series and label lookups from block indexes.

=== `caches.metadata`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
caches:
  metadata:
    enabled: true
----

Using the metadata cache reduces the number of API calls to long-term storage and stops the number of the API calls that scale linearly with the number of querier and store-gateway replicas.

=== `caches.results`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
caches:
  results:
    enabled: true
----


== `global`

Configure global settings.

=== `global.nodeSelector`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
global:
  nodeSelector: {}
----
example::
+
[source,yaml]
----
global:
  nodeSelector:
    appuio.io/node-class: plus
----

Node selector configuration which is used for each component's `nodeSelector` field in parameter `helm_values`.

This value is used verbatim as a Kubernetes node selector.

=== `global.zoneAwareReplication`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
global:
  zoneAwareReplication:
    enabled: false
    zones: []
----
example::
+
[source,yaml]
----
global:
  zoneAwareReplication:
    enabled: true
    zones:
      - name: zone-a
        nodeSelector:
          topology.kubernetes.io/zone: 'zone-a'
      - name: zone-b
        nodeSelector:
          topology.kubernetes.io/zone: 'zone-b'
      - name: zone-c
        nodeSelector:
          topology.kubernetes.io/zone: 'zone-c'
----

Zone-aware replication is the replication of data across failure domains.
Zone-aware replication helps to avoid data loss during a domain outage. Grafana Mimir defines failure domains as zones. 

=== `global.nginxResolverOverride`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
global:
  nginxResolverOverride: ''
----
example::
+
[source,yaml]
----
global:
  nginxResolverOverride: '172.30.0.10'
----

If set, the nginx resolver is set to this value.
This can be used to insert the static IP of the cluster DNS server, which will fix the case when the resolved DNS service IP changes, but nginx keeps the old IP.


== `config`

General configuration options for Mimir.

=== `config.tenantFederation`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
config:
  tenantFederation: false
----

Mimir ruler tenant federation is a Mimir feature enabling recording and alerting rules to query and aggregate data across multiple tenant isolation boundaries.

=== `config.haTracker`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
config:
  haTracker: false
----

The Mimir HA Tracker is a component of the Mimir distributor that deduplicates incoming metrics from multiple Prometheus/Alloy replicas, ensuring identical time series sent by HA pairs are only stored once.

=== `config.haLabels`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
config:
  haLabels:
    cluster: cluster_id
    replica: prometheus_replica
----

The labels by which incoming metrics are deduplicated.

=== `config.haStore`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
config:
  haStore:
    type: etcd
----
default::
+
[source,yaml]
----
config:
  haStore:
    type: etcd
    endpoints:
      - https://mimir-kv-etcd-0.mimir-kv-etcd-headless.mimir-kv:2379
      - https://mimir-kv-etcd-1.mimir-kv-etcd-headless.mimir-kv:2379
      - https://mimir-kv-etcd-2.mimir-kv-etcd-headless.mimir-kv:2379
    tls_enabled: true
    tls_insecure_skip_verify: true
    # (swi): feels wrong but we use the etcd exclusivly for mimir and don't currently have a way to provision other users
    username: root
    password: '?{vaultkv:${cluster:tenant}/${cluster:name}/mimir-kv/etcd_root_password}'
----

The HA tracker requires a key-value (KV) store to coordinate which replica is currently elected.
See https://grafana.com/docs/mimir/latest/configure/configure-high-availability-deduplication/#configure-the-ha-tracker-kv-store[Mimmir documentation] for details.

IMPORTANT: The key-value store has to be setup seperatly!


== `secrets`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
secrets: {}
----

A dict of secrets to create in the namespace. The key is the name of the secret, the value is the content of the secret.
The value must be a dict with a key `stringData` which is a dict of key/value pairs to add to the secret.


== `monitoring`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
monitoring: true
----

Enable the service monitors, rules, and alerts from the Helm chart.


== `alerts`

Configurations related to alerts.

=== `alerts.patchRules`

[horizontal]
type:: dict
default:: https://github.com/projectsyn/component-mimir/blob/master/class/defaults.yml[See `class/defaults.yml`]
example::
+
[source,yaml]
----
alerts:
  patchRules:
    ignoreNames:
      - MimirContinuousTestNotRunningOnWrites
    patches:
      MimirInconsistentRuntimeConfig:
        for: 15m
----

This parameter allows users to patch or remove alerts provided by the upstream Mimir chart.

The values in the `ignoreNames` parameter correspond to the field `alert` of the alert to ignore.

The keys in the `patches` parameter correspond to the field `alert` of the alert to patch.
The component expects valid partial Prometheus alert rule objects as values.

IMPORTANT: The provided values aren't validated, they're applied to the corresponding upstream alert as-is.

=== `alerts.additionalRules`

[horizontal]
type:: dict
default:: https://github.com/projectsyn/component-mimir/blob/master/class/defaults.yml[See `class/defaults.yml`]
example::
+
[source,yaml]
----
alerts:
  additionalRules:
    "alert:CustomTestAlert":
      expr: vector(1) == 0
      for: 1h
      annotations:
        summary: Test alert
      labels:
        severity: warning
----

This parameter allows users to configure additional alerting and recording rules.
All rules defined in this parameter will be added to rule group `mimir-custom.rules`.


== `helm_values`

[horizontal]
type:: dict
default:: see https://github.com/projectsyn/component-mimir/blob/master/class/defaults.yml[class/defaults.yml]

Holds the values for the helm chart.

The defaults are close to the upstream defaults, with HA enabled, and the bucket secret added.
Replicas and resource limits/requests are taken from the `small.yaml` recommended production values.

The read path, especially the `store-gateway`, doesn't have HA enabled.
There is no data loss, but there is a performance impact.

See https://grafana.com/docs/mimir/latest/operators-guide/run-production-environment/planning-capacity/[Planning capacity], https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/small.yaml[small.yaml], and https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/large.yaml[large.yaml] for upstream sizing recommendations.

https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/[Components] describes what the components enabled by this Helm chart do.

https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/ingester/#ingesters-failure-and-data-loss[Ingester failure and data loss] describes the implications of a HA setup.

== Example

[source,yaml]
----
namespace:
  name: example-mimir
  create: true
  metadata:
    labels:
      example.com/organization: example

secrets:
  mimir-nginx-htpasswd:
    stringData:
      .htpasswd: "?{vaultkv:${cluster:tenant}/${cluster:name}/example-mimir/htpasswd}"

helm_values:
  nginx:
    basicAuth:
      enabled: true
      existingSecret: mimir-nginx-htpasswd
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      enabled: true
      hosts:
        - host: mimir.example.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: example-mimir-tls
          hosts:
            - mimir.example.com
----
