= Upgrade component version v3 to v4

Version 4.x is a major overhaul of the configuration parameters of the component,
https://github.com/projectsyn/component-mimir/releases/tag/v4.0.0[see Release Notes] for more details.

The component has lots of options to configure each part of the Mimir installation.
Please have a look at the xref:references/parameters.adoc[parameters documentation] for reference.

[IMPORTANT]
====
This component will automatically migrate to the unified gateway deployment.
See xref:how-tos/migrate-to-gateway.adoc[] for further instructions.
====

[IMPORTANT]
====
This component will no longer support Helm charts < v5.x of Mimir.
====


== Explanation of configuration changes

=== new namespace naming

[IMPORTANT]
====
This component will change the default name of the namespace to the instance name.
It is also no longer allowed to configure an non-instantiated version.
====

If you have configured a namespace name that is different than the instance name, then change the namespace name here:

[source,yaml]
----
namespace:
  name: ${_instance} <1>
----
<1> Overwrite the default namespace name.

If you have configured the component in a non-instantiated version, then change the following:

[source,yaml]
----
applications:
  - mimir as your-new-instance-name <1>

parameters:
  your_new_instance_name: <2>
    namespace:
      name: ${_instance} <3>
----
<1> Redefine the component include in `applications`.
<2> Rename the component configuration as your new instance name.
<3> Overwrite the default namespace name.

=== new default resource requests

[IMPORTANT]
====
This component changes its default resource requests and limits, please check the output of your catalog compilation and adjust if needed.
See xref:references/parameters.adoc#_components[components] and xref:references/parameters.adoc#_caches[caches] to adjust your settings.
====

This component supports the following presets:

* `none`: Use the Helm charts defaults.
* `extra-small`: Component defaults for small production deployments (default).
* `small`: Upstream defaults for small production deployments.
* `large`: Upstream defaults for large production deployments.

=== legacy `globalNodeSelector`

The values for the global node selector has moved to `global.nodeSelector`.

[TIP]
====
This change is backward compatible, but migrating the values to the new structure is recommended.
====

=== legacy `nginx_resolver_override`

The values for the nginx dns resolver override has moved to `global.nginxResolverOverride`.

[TIP]
====
This change is backward compatible, but migrating the values to the new structure is recommended.
====
